services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    image: "${DOCKER_HUB_USERNAME}/nestjs-app:latest"
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
