export enum STATUS {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
}
export enum PAYMENT_METHOD {
  QR_CODE = 'QR_CODE',
  E_WALLET = 'E_WALLET',
}

export enum QUESTION_TYPE {
  COMBO_BOX = 'COMBO_BOX',
  BLANK = 'BLANK',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
}

export enum SECTION_TYPE {
  ROOT = 'ROOT',
  READING = 'READING',
  LISTENING = 'LISTENING',
  VOCABULARY = 'VOCABULARY',
}
